const columnWidthConfig = [
  { columnName: "email", width: 250 },
  { columnName: "discord", width: 200 },
  { columnName: "discord_id", width: 200 },
  { columnName: "team_name", width: 200 },
  { columnName: "name", width: 200 },
  { columnName: "start_date", width: 200, wordWrapEnabled: true },
  { columnName: "end_date", width: 200, wordWrapEnabled: true },
  { columnName: "track", width: 100 },
  { columnName: "goals", width: 200 },
  { columnName: "lang_prefs", width: 250, wordWrapEnabled: true },
  { columnName: "interest_skills", width: 200, wordWrapEnabled: true },
  { columnName: "region", width: 200 },
  { columnName: "location", width: 200 },
  { columnName: "pronouns", width: 200 },
  { columnName: "introduction", width: 400, wordWrapEnabled: true },
  { columnName: "five_years", width: 200 },
  { columnName: "year_school", width: 200 },
  { columnName: "lang_importance", width: 200 },
  { columnName: "team_lead", width: 200 },
  { columnName: "hours_per_week", width: 200 },
  { columnName: "commitment_lev", width: 200 },
  { columnName: "commitment_exp", width: 200 },
  { columnName: "meet_per_week", width: 200 },
  { columnName: "curr_responsible", width: 200 },
  { columnName: "bring_to_team", width: 200 },
  { columnName: "professional_link", width: 200 },
  { columnName: "demographics", width: 250, wordWrapEnabled: true },
  { columnName: "partner_prefs", width: 400, wordWrapEnabled: true },
  { columnName: "commit_agreement", width: 200 },
  { columnName: "team_agreement", width: 200 },
  { columnName: "rules_agreement", width: 200 },
  { columnName: "tips", width: 200 },
  { columnName: "createdAt", width: 200, wordWrapEnabled: true },
  { columnName: "updatedAt", width: 200, wordWrapEnabled: true },
  { columnName: "__v", width: 200 },
];

export default columnWidthConfig;
